### ISSUE TITLE
Malware detected

### ISSUE THREAD

**Issue by Paldrus** [sanraith/razer-taskbar#13]
![Snímka obrazovky 2024-06-17 205744](https://github.com/sanraith/razer-taskbar/assets/122242393/ab5a1f38-c506-4a33-a86b-83eb18bda2f2)
Latest update (v0.11.0 setup.exe) got Trapmine inside according to VirusTotal.

**Comment by sanraith** [comment]
"Trapmine" is the name of the company that provided that particular scan. [Virustotal](https://www.virustotal.com/gui/file/3be88ab5e00e7d64a7db2280c257ffa6c84dc1a415e5717ef9d3e6e3b91cb116/detection)  
Both of the triggers are heuristic ones. This does not suprise me since the main purpose of this app is to "spy" on Razer Synapse.

The app is open source, so you are welcome to point out the problematic part in this repo or the dependencies if you think there is one.

**Comment by Paldrus** [comment]
Just wanted to be sure, thank you!
